# Generated by Django 3.2.4 on 2021-06-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdapp', '0003_auto_20210627_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='mailbox_email',
        ),
        migrations.AddField(
            model_name='ticket',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='subject',
            field=models.CharField(default='', max_length=191),
            preserve_default=False,
        ),
    ]
