# Generated by Django 3.2.4 on 2021-06-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdapp', '0004_auto_20210627_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='gender',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
    ]
